Solve #104 Documentação Review Sprint 4
fga-eps-mds/2020.2-Eccoar pull request #107
Opened 2021-03-15 21:09 UTC by Phe0

## Conteúdo
Documentação da review e retrospectiva da Sprint 4

Neste pull request se realizou:
* Documentação da Review
* Documentação da retrospectiva

## Checklist 
- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo: 

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:
* Solve #X IssueName (Caso Padrão)
* WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-03-16 03:35 UTC, devsalula requested changes
Parabéns pelo trabalho. Apenas alguns pontos para corrigir.

2021-03-16 03:35 UTC, devsalula commented on docs/sprints/4/review.md
> +- A sprint foi marcada pela saída de um dos membros d grupo de MDS, o que afetou um pouco a moral do time.
"membros d grupo"

2021-03-16 03:35 UTC, devsalula commented on docs/sprints/4/review.md
> +- Houveram duas issues que se tornaram dívida técnica novamente, isso se dev bastante ao fato dos membros estarem deixando pra realizar as tarefas no final da sprint, não levando em consideração
"isso se dev bastante"

2021-03-16 03:35 UTC, devsalula commented on docs/sprints/4/review.md
> +- Durante a reunião da sprint foi levantado o problema de faltade organização com arquivos CSS/SASS, como solução foi proposta uma nova arquitetura para melhorar esse problema, com isso será re
"problema de faltade organização"

2021-03-16 03:35 UTC, devsalula commented on docs/sprints/4/review.md
> +- Houve um aumento bastante relevante no tempo de início das tarefas até o final, principalmente no tempo em que a tarefa está ficando em revisão. Isso está acontecendo por conta do início das
"conta do início das atividades se utilizando código"

2021-03-16 03:35 UTC, devsalula commented on docs/sprints/4/review.md
> +- O humor do time diminuiu bastante, isso se deve a problemas pessoais de alguns membros membros, além da saída de um MDS da equipe e alguns membros relataram cansaço e falta de tempo durante a sp
"pessoais de alguns membros membros"

2021-03-18 17:16 UTC, Phe0 commented
arrumei os erros @devsalula

2021-03-18 17:22 UTC, MatheusBlanco approved these changes

2021-03-18 19:20 UTC, devsalula approved these changes

2021-03-18 19:20 UTC, merged