Solve #135 Documentação Planning 7
fga-eps-mds/2020.2-Eccoar pull request #136
Opened 2021-03-29 19:06 UTC by MatheusBlanco

Neste pull request se realizou:
* Adiciona documentação da planning da sprint 7 do projeto

## Checklist 
- [ ] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [ ] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ ] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [ ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ ] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-04-01 02:28 UTC, devsalula requested changes

2021-04-01 02:28 UTC, devsalula commented on docs/sprints/7/planning.md
> +| [US26 - Detalhamento da denúncia](https://github.com/fga-eps-mds/EPS-2020-2-G2/issues/124)                    | 13     | Arthur Matos, Brian Pina e Saleh Kader |
O nome dessa issue não está errada?

2021-04-01 02:28 UTC, devsalula commented on docs/sprints/7/planning.md
> +- Uma das equipes foi montada com um membro de EPS e um membro de MDS, para que o membro de MDS não se sobrecarregasse em suas atividades.
"2 membros de MDS"

2021-04-02 21:33 UTC, MatheusBlanco commented
@devsalula , resolvido

2021-04-03 02:34 UTC, devsalula approved these changes

2021-04-03 02:34 UTC, merged