Solve #134 Sprint review 6
fga-eps-mds/2020.2-Eccoar pull request #137
Opened 2021-04-01 16:32 UTC by Phe0

## Conteúdo
Retrospectiva e review da sprint 6
Add novo membro na introdução e na home

Neste pull request se realizou:
* US 00
* Testes
* Correção de bug ao...

2021-04-03 12:05 UTC, MatheusBlanco requested changes
Parabéns! Só queria requisitar a mudança apontada

2021-04-03 12:05 UTC, MatheusBlanco commented on docs/sprints/6/retrospectiva.md
> +- As dailiesestão sendo pouco informativas e nem sempre estão sendo respondidas, por conta disso o grupo optou por realizar um ponto de controle via chamada no meio da sprint;
dailiesestão

2021-04-08 20:51 UTC, Phe0 commented
arrumei @MatheusBlanco

2021-04-09 12:52 UTC, MatheusBlanco approved these changes

2021-04-09 12:52 UTC, merged