Solve #133 Cálculo de quantidade de votos
fga-eps-mds/2020.2-Eccoar pull request #150
Opened 2021-04-03 21:32 UTC by MatheusBlanco

## Conteúdo
Criação do documento em que se explica a pesquisa e o cálculo para se saber a quantidade de votos necessária para o sistema de denúncias

Neste pull request se realizou:
* Adição do documento

## Checklist 
- [ ] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [ ] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [ ] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [ ] Adicionar a sprint correspondente à execução das modificações (Milestone).
- [ ] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [ ] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [ ] Escrever o título do pull request no formato correto, conforme as referências abaixo:

2021-04-04 15:06 UTC, devsalula requested changes

2021-04-04 15:06 UTC, devsalula commented on docs/produto/extras/calculoVotos.md
> +- Pesquisa de densidade demográfica do DF. A partir do estudo de um censo [1] das regiões administrativas do DF, pudemos ter um paronama geral da quantidade de pessoas moradoras em uma área de 1 héct
Faz a tabela em markdown rs

2021-04-04 20:03 UTC, MatheusBlanco commented
feito kk

Em dom., 4 de abr. de 2021 às 12:06, Saleh Kader ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In docs/produto/extras/calculoVotos.md
> <https://github.com/fga-eps-mds/2020.2-Eccoar/pull/150#discussion_r606814047>
> :
>
> > +
>
> +Um dos objetivos do projeto _Eccoar_ é impulsionar e dar visibilidade para as denúncias criadas pelos usuários. Para que possamos realizar esse impulsionamento, trabalhamos com um sistema de votos, onde existem dois tipos diferentes:
>
> +
>
> +- Os votos de impulsionamento de existência de denúncias, quando a denúncia se encontra em status _open_
>
> +- Os votos de confirmação de resolução da denúncia em questão, quando a denúncia se encontra em status _wait_ (aguardando)
>
> +
>
> +A partir do alcance de um determinado número de votos, os mesmos realizados pela população usuária do sistema, o voto sofre uma ação. Se o voto for no status _open_ e sua quantidade atingir um certo número, a denúncia em questão será transformada em um PDF, e o mesmo será enviado para o órgão em questão. Se o voto for no status _wait_ e atingir a mesma quantidade, a denúncia será considerada resolvida e não aparecerá mais para seus usuários.
>
> +
>
> +Entende-se que a quantidade de votos de uma denúncia é de considerável importância para que o sistema atinja seus objetivos. E como a quantidade de votos depende da quantidade de usuários, consideramos importante levantar um cálculo baseado em pesquisas que demonstre quantos votos, em média, seriam ideais para que uma denúncia seja impulsionada da maneira adequada.
>
> +
>
> +## A pesquisa
>
> +
>
> +Para se alcançar uma fórmula satisfatória e que representasse da melhor maneira os votos em uma denúncia, realizamos uma pesquisa baseada em três pilares. São eles:
>
> +
>
> +- Entendimento de interação da população do DF com o aplicativo _Colab_, que por ser nosso concorrente possui uma missão e um sistema de funcionamento parecido. A partir da utilização do Colab e do estudo das regularidades do mesmo, entendemos que em média, 3 a 6 pessoas interagiam com uma denúncia, em um contexto de aproximadamente 1097 usuários (na data da criação da conta e desse estudo). Definimos o valor de 6 votos como o valor base para nossos cálculos por hora, entretanto este número pode variar em cenários ou tempos diferentes;
>
> +- Pesquisa de densidade demográfica do DF. A partir do estudo de um censo [1] das regiões administrativas do DF, pudemos ter um paronama geral da quantidade de pessoas moradoras em uma área de 1 héctare (10 mil m²). Os resultados foram anotados em uma [tabela](https://docs.google.com/document/d/1XNyyUlRmfW0P4hhyy5SEMRSILI2vUtCO8WhCaj4CLtU/edit?usp=sharing) e utilizados para o cálculo posterior;
>
>
> Faz a tabela em markdown rs
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fga-eps-mds/2020.2-Eccoar/pull/150#pullrequestreview-627547840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI5GFNNDMOVMX3LTPEKD2CLTHB56RANCNFSM42KUZNDQ>
> .
>

2021-04-05 17:46 UTC, devsalula requested changes

2021-04-05 17:46 UTC, devsalula commented on docs/produto/extras/calculoVotos.md
> +- Pesquisa de densidade demográfica do DF. A partir do estudo de um censo [1] das regiões administrativas do DF, pudemos ter um paronama geral da quantidade de pessoas moradoras em uma área de 1 héct
@MatheusBlanco não querendo ser chato. Mas remove o link para o documento aqui pfvr.

2021-04-05 23:59 UTC, devsalula approved these changes

2021-04-05 23:59 UTC, merged