Sprint review 7
fga-eps-mds/2020.2-Eccoar pull request #152
Opened 2021-04-08 21:55 UTC by Phe0

## Conteúdo
Documentação da sprint 7 e atualização do readme.

Neste pull request se realizou:
* Doc Review Sprint 07
* Doc Retrospectiva Sprint 07
* Link dos repositórios e org no readme
* Novo membro no readme

2021-04-09 04:40 UTC, devsalula requested changes

2021-04-09 04:40 UTC, devsalula commented on docs/sprints/7/review.md
> +- Estamosvindo em uma sequência de sprints com muita dívida técnica, o que tem acontecido é que muitas issues estão sendo terminadas no começo da sprint seguinte. Para enfrentar esse risco deci
Estamosvindo, quea

2021-04-09 04:40 UTC, devsalula commented on docs/sprints/7/review.md
> +- O quadro de conhecimento continua subindo, mesmo com o novo integrante, o que mostra o constate crescimento da equipe;
Constate

2021-04-09 20:02 UTC, Phe0 commented
arrumei os erros @devsalula

2021-04-09 22:26 UTC, MatheusBlanco approved these changes

2021-04-10 14:18 UTC, devsalula approved these changes

2021-04-10 14:19 UTC, merged