Solve #189 Documentar review da sprint 10
fga-eps-mds/2020.2-Eccoar pull request #190
Opened 2021-04-26 21:22 UTC by Phe0

## Conteúdo
Documentação referente aos acontecimentos da sprint 10

Neste pull request se realizou:
* Documentação Sprint Review 10
* Documentação Sprint Retrospective 10
* Mudança de cor do ícone de busca da wiki

## Checklist 
- [x] Indicar pelo menos um membro da equipe de EPS a ser responsável por analisar as modificações submetidas (Reviewers). 
- [x] Indicar os membros da equipe que contribuíram com as modificações realizadas (Assignees).
- [x] Adicionar as labels referentes ao pull request, de forma similar às da issue correspondente (Labels).
- [x] Conectar o PR à sua issue correspondente através da interface do Github (Connect Issue). 
- [x] Indicar no título do pull request o número e o nome da issue a qual ele se refere.
- [x] Escrever o título do pull request no formato correto, conforme as referências abaixo: 

O pull request deve indicar em seu título o número e o nome da issue ao qual issue se refere, em algum dos formatos abaixo:
* Solve #X IssueName (Caso Padrão)
* WIP #X IssueName, para indicar que o pull request ainda não está completo para o merge (Work in Progress).

2021-04-28 22:33 UTC, MatheusBlanco requested changes
Parabéns @Phe0 ! Só arrumar o que pedi aqui e merjo

2021-04-28 22:33 UTC, MatheusBlanco commented on docs/sprints/10/review.md
> +- Um novo risco de PRs não revisados foi destacado, vários PRs estão demorando para serem revisados, muito dsso é devido a parte de responsabilidade de revisão ter sido passada aos MDS, que aind
dsso

2021-04-28 22:33 UTC, MatheusBlanco commented on docs/sprints/10/review.md
> +- Os membros responsáveis pel tarefa [US - Autenticação de usuário](https://github.com/fga-eps-mds/EPS-2020-2-G2/issues/165) tiveram bastante dificuldade com o Firebase, nova ferramenta adotada pela
pel

2021-04-29 17:04 UTC, Phe0 commented
prontinho @MatheusBlanco

2021-04-29 19:06 UTC, MatheusBlanco approved these changes

2021-04-29 19:06 UTC, merged